import turtle
pen =turtle.Pen()
pen.width(4)
pen.color('red')
pen.left(130)
pen.forward(80)
pen.right(90)
pen.forward(160)
pen.right(85)
pen.forward(80)
pen.color('blue')
pen.left(85)
pen.forward(80)
pen.right(85)
pen.forward(160)
pen.right(93)
pen.forward(80)
pen.shape('blank')

turtle.done()
